#!/usr/bin/env bash
# Automystics — one-time VPS setup script (Ubuntu 22.04 / 24.04).
#
# Usage (run as root or with sudo from the repo root):
#   sudo bash deploy/setup.sh
#
# What this does:
#   1. Installs Node 20, Nginx, PostgreSQL, pnpm, PM2
#   2. Creates the PostgreSQL user + database
#   3. Prompts for secrets and writes artifacts/api-server/.env
#   4. Installs dependencies and builds the API + frontend
#   5. Pushes the database schema (drizzle-kit push --force)
#   6. Configures Nginx and opens the firewall
#   7. Starts the API under PM2 and enables it on boot
#
# After this runs, use  bash deploy/deploy.sh  for every subsequent update.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/artifacts/api-server/.env"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33mWARN: %s\033[0m\n' "$1"; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

# ── root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  die "Run this script as root:  sudo bash deploy/setup.sh"
fi

cd "$REPO_ROOT"
log "Repo: $REPO_ROOT"

# ── 1. System packages ─────────────────────────────────────────────────────────
log "Installing system packages (Node 20, Nginx, PostgreSQL, build tools)"

apt-get update -qq

if ! command -v node &>/dev/null || [[ "$(node -e 'process.stdout.write(process.version.split(".")[0].replace("v",""))')" -lt 20 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null
fi

apt-get install -y -qq nodejs build-essential git nginx postgresql postgresql-contrib

# pnpm
if ! command -v pnpm &>/dev/null; then
  npm install -g pnpm@9 --quiet
fi

# pm2
if ! command -v pm2 &>/dev/null; then
  npm install -g pm2 --quiet
fi

log "Node $(node -v) | pnpm $(pnpm -v) | pm2 $(pm2 -v)"

# ── 2. Log directory ───────────────────────────────────────────────────────────
mkdir -p /var/log/automystics

# ── 3. Collect secrets interactively ──────────────────────────────────────────
log "Configuration — enter values when prompted (input is hidden)"

read -rsp "PostgreSQL password for the 'automystics' DB user: " DB_PASSWORD; echo
[[ -z "$DB_PASSWORD" ]] && die "DB password cannot be empty."

SESSION_SECRET="$(openssl rand -base64 48)"
echo "Session secret: auto-generated (64 random bytes)."

read -rsp "Admin password for /admin (leave blank for built-in default — change before going live): " ADMIN_PASSWORD; echo
ADMIN_USERNAME="admin"

read -rp  "Domain or IP for Nginx (e.g. automystics.com or 203.0.113.42): " SERVER_HOST
[[ -z "$SERVER_HOST" ]] && die "Domain/IP cannot be empty."

read -rp  "Set up HTTPS with Let's Encrypt? Requires a real domain pointed at this server. [y/N]: " SETUP_HTTPS
SETUP_HTTPS="${SETUP_HTTPS,,}"

DATABASE_URL="postgresql://automystics:${DB_PASSWORD}@127.0.0.1:5432/automystics"

# ── 4. PostgreSQL — create user + database ─────────────────────────────────────
log "Creating PostgreSQL user and database"

systemctl is-active --quiet postgresql || systemctl start postgresql

# Create user (ignore if it already exists)
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='automystics'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE USER automystics WITH PASSWORD '${DB_PASSWORD}';"

# Update password in case it changed
sudo -u postgres psql -c "ALTER USER automystics WITH PASSWORD '${DB_PASSWORD}';"

# Create database (ignore if it already exists)
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='automystics'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE automystics OWNER automystics;"

sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE automystics TO automystics;"

# Verify connectivity
psql "$DATABASE_URL" -c '\conninfo' >/dev/null || die "Cannot connect to PostgreSQL with the provided password."
echo "PostgreSQL connection verified."

# ── 5. Write .env ──────────────────────────────────────────────────────────────
log "Writing $ENV_FILE"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup.sh — keep this file private (chmod 600).

DATABASE_URL=${DATABASE_URL}
SESSION_SECRET=${SESSION_SECRET}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-Automystics@2026}
NODE_ENV=production
PORT=8080
LOG_LEVEL=info
EOF

chmod 600 "$ENV_FILE"
echo "Written and locked to root-only (600)."

# ── 6. Install dependencies + build ───────────────────────────────────────────
log "Installing pnpm dependencies (frozen lockfile)"
pnpm install --frozen-lockfile

log "Building API server → artifacts/api-server/dist/index.mjs"
pnpm --filter @workspace/api-server build

log "Building frontend → artifacts/automystics/dist/public"
PORT=8090 BASE_PATH=/ pnpm --filter @workspace/automystics build

# ── 7. Push database schema ────────────────────────────────────────────────────
log "Pushing database schema (drizzle-kit push --force)"
DATABASE_URL="$DATABASE_URL" pnpm --filter @workspace/db exec drizzle-kit push --force

# ── 8. Nginx configuration ─────────────────────────────────────────────────────
log "Configuring Nginx for $SERVER_HOST"

# Create logs directory next to the repo (used by ecosystem.config.cjs)
mkdir -p "$REPO_ROOT/logs"

NGINX_CONF="/etc/nginx/sites-available/automystics"
cp "$REPO_ROOT/deploy/nginx.conf" "$NGINX_CONF"
sed -i "s|YOUR_SERVER_IP_OR_DOMAIN|${SERVER_HOST}|g" "$NGINX_CONF"
sed -i "s|REPO_ROOT_PLACEHOLDER|${REPO_ROOT}|g" "$NGINX_CONF"

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/automystics
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl reload nginx
echo "Nginx configured and reloaded."

# ── 9. Firewall ────────────────────────────────────────────────────────────────
if command -v ufw &>/dev/null; then
  log "Opening firewall ports (Nginx Full = 80 + 443)"
  ufw allow 'Nginx Full' --quiet || warn "ufw allow failed — check firewall manually."
fi

# ── 10. PM2 — start API + persist across reboots ──────────────────────────────
log "Starting API under PM2"

if pm2 describe automystics-api &>/dev/null; then
  pm2 reload automystics-api --update-env
else
  pm2 start "$REPO_ROOT/deploy/ecosystem.config.cjs" --update-env
fi

pm2 save

# Enable PM2 on boot (prints a command the user must run as root; we capture + run it)
STARTUP_CMD="$(pm2 startup systemd -u root --hp /root 2>&1 | grep 'sudo env' | head -1)"
if [[ -n "$STARTUP_CMD" ]]; then
  eval "$STARTUP_CMD" || warn "Could not register PM2 startup — run manually: $STARTUP_CMD"
fi

# ── 11. Health check ───────────────────────────────────────────────────────────
log "Health check"
sleep 2

if curl -fsS http://127.0.0.1:8080/api/healthz >/dev/null; then
  echo "API is healthy."
else
  warn "Health check failed. Check logs: pm2 logs automystics-api --lines 50"
fi

# ── 12. HTTPS (optional) ───────────────────────────────────────────────────────
if [[ "$SETUP_HTTPS" == "y" ]]; then
  log "Setting up HTTPS with Let's Encrypt (certbot)"
  apt-get install -y -qq certbot python3-certbot-nginx
  certbot --nginx -d "$SERVER_HOST" --non-interactive --agree-tos -m "admin@${SERVER_HOST}" \
    || warn "Certbot failed — ensure DNS is pointed at this server and port 80 is reachable, then run: certbot --nginx -d $SERVER_HOST"
fi

# ── Done ───────────────────────────────────────────────────────────────────────
log "Setup complete"
pm2 status automystics-api

cat <<MSG

  Site:   http://${SERVER_HOST}/
  Admin:  http://${SERVER_HOST}/admin/login
  Logs:   pm2 logs automystics-api

  To deploy updates:
    cd $REPO_ROOT && bash deploy/deploy.sh
    bash deploy/deploy.sh --migrate    # if the DB schema changed

MSG
